// Synthetic local records only; never use the owner's database.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const base='http://127.0.0.1:8098',headers={'X-Requested-With':'wasool'},checks=[];
const out=path.resolve('data/cancel-qa');fs.mkdirSync(out,{recursive:true});
const plan=()=>({id:'qa-cancel-c',kind:'monthly',cycle:'monthly',packageId:'pkg_c',currency:'PKR',start:'2026-09-01',prorate:true,prorationBasis:'fixed30',prorationDaysOverride:24,prices:[{from:'2026-09-01',price:4200}],payments:[{id:'receipt-1',date:'2026-09-01',amount:4200,currency:'PKR',rate:null,note:'Original receipt'}],refunds:[{id:'refund-1',date:'2026-09-23',amount:840,currency:'PKR',rate:null,note:'Original refund'}]});
const fixture=()=>({name:'Cancellation QA',email:'cancel-qa@example.test',joinDate:'2026-09-01',subscriptions:[plan()]});
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.PLAYWRIGHT_EXECUTABLE,args:['--disable-gpu']});
 try {
 const context=await browser.newContext({viewport:{width:1400,height:1000},colorScheme:'light'});await context.addInitScript(()=>localStorage.setItem('pt-today','2026-10-05'));
 const page=await context.newPage();const errors=[];let failing=false;page.on('pageerror',e=>errors.push(e.stack));page.on('console',m=>{if(m.type()==='error'&&!(failing&&m.text().includes('503')))errors.push(m.text())});
 await page.goto(base+'/login',{waitUntil:'domcontentloaded'});await page.locator('[name=passcode]').fill('test1234');await page.locator('button[type=submit]').click();await page.waitForSelector('#tbody tr.row');
 await page.waitForTimeout(1000);errors.length=0;assert.equal((await (await context.request.get(base+'/healthz')).json()).version,'34');
 const put=async user=>assert.equal((await context.request.put(base+'/api/docs/users/qa-cancel',{headers,data:user})).status(),200);
 const get=async()=>(await (await context.request.get(base+'/api/docs/users/qa-cancel')).json()).data;
 const row=()=>page.locator('tr.row[data-id="qa-cancel"]');const det=()=>page.locator('tr.detail[data-id="qa-cancel"]');const form=()=>det().locator('.cancel-form');
 const reset=async user=>{await put(user);await page.reload({waitUntil:'domcontentloaded'});await page.locator('#statusFilter').selectOption('all');await row().waitFor();await row().click();await det().waitFor()};
 const open=async()=>{await det().locator('[data-key=cancel]').first().click();await form().waitFor({state:'visible'})};
 const month=async value=>{await form().locator('[name=cancelMonth]').fill(value);await form().locator('[name=cancelMonth]').dispatchEvent('change')};
 const save=async()=>{await form().locator('button[type=submit]').click();try{await form().waitFor({state:'hidden',timeout:6000})}catch(e){console.error('Browser errors:',errors);console.error('Form:',await form().innerText());console.error('Saved cutoff:',(await get()).cancel?.lastDay);throw e}};
 const record=(name)=>checks.push({name,passed:true});
 let user=fixture();await reset(user);await open();await month('2026-09');assert.equal(await form().locator('[name=lastDay]').inputValue(),'2026-09-23');assert.match(await form().locator('[data-role=cancel-preview]').innerText(),/Settled: nothing owed/);await save();let saved=await get();assert.equal(saved.cancel.lastDay,'2026-09-23');assert.deepEqual(saved.subscriptions[0].payments,user.subscriptions[0].payments);assert.deepEqual(saved.subscriptions[0].refunds,user.subscriptions[0].refunds);assert.match(await det().locator('.cancel-note').innerText(),/settled, nothing owed/);record('New cancellation before September bill keeps receipts/refunds and clears future dues');
 user=fixture();user.cancel={lastDay:'2026-09-24',at:'2026-09-24',reason:'Original cancellation',note:'Original note'};user.subscriptions[0].end='2026-09-24';
 const earlier={...plan(),id:'qa-earlier',end:'2026-09-10',prices:[{from:'2026-09-01',price:0}],payments:[],refunds:[]};const later={...plan(),id:'qa-future',start:'2026-10-01',end:'2026-09-24',payments:[],refunds:[]};user.subscriptions.push(earlier,later);
 await reset(user);assert.match(await det().locator('.cancel-note').innerText(),/4,200/);await open();await month('2026-09');await form().locator('[name=reason]').fill('Corrected final billing month');
 await page.locator('#search').fill('Cancellation');assert.equal(await form().locator('[name=lastDay]').inputValue(),'2026-09-23');assert.equal(await form().locator('[name=reason]').inputValue(),'Corrected final billing month');record('Draft survives a table redraw');
 failing=true;await page.route('**/api/docs/users/qa-cancel',async route=>route.request().method()==='PUT'?route.fulfill({status:503,contentType:'application/json',body:'{"error":"Synthetic failure"}'}):route.continue());await form().locator('button[type=submit]').click();await page.waitForTimeout(400);assert.equal(await form().isVisible(),true);assert.equal(await form().locator('[name=lastDay]').inputValue(),'2026-09-23');assert.equal((await get()).cancel.lastDay,'2026-09-24');await page.unroute('**/api/docs/users/qa-cancel');failing=false;await save();saved=await get();assert.equal(saved.subscriptions[1].end,'2026-09-10');assert.equal(saved.subscriptions[2].end,'2026-09-23');assert.match(await det().locator('.cancel-note').innerText(),/settled, nothing owed/);assert.equal(saved.cancelHistory?.length||0,0);record('Edit cancellation retries failed save, preserves separate ends, and excludes future starts');
 for(const width of [390,1400])for(const theme of ['light','dark']){await page.setViewportSize({width,height:1000});await page.emulateMedia({colorScheme:theme});await page.evaluate(t=>document.documentElement.dataset.theme=t,theme);await open();await month('2026-09');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),width);await form().scrollIntoViewIfNeeded();await page.screenshot({path:path.join(out,`cancel-${width}-${theme}.png`)});await form().locator('[data-key=cancel]').click();record(`Cancellation form ${width}px ${theme} fits`)}
 await page.locator('#search').fill('');user=fixture();user.subscriptions[0].payments=[];user.subscriptions[0].refunds=[];await reset(user);await open();await month('2026-09');assert.match(await form().locator('[data-role=cancel-preview]').innerText(),/Earlier bills still owed: Rs 3,360/);await save();assert.match(await det().locator('.cancel-note').innerText(),/still owes Rs 3,360/);record('Genuine earlier arrears are not forgiven');
 user=fixture();user.subscriptions[0].start='2026-08-24';delete user.subscriptions[0].prorationDaysOverride;await reset(user);await open();await month('2026-09');assert.match(await form().locator('[data-role=cancel-preview]').innerText(),/Settled: nothing owed/);await save();saved=await get();assert.equal(saved.subscriptions[0].periodOverrides['2026-08-24'].amount,3360);assert.equal(saved.subscriptions[0].periodOverrides['2026-08-24'].fromRefund,true);record('Refund made before cancellation is settled during cancellation save');
 user=fixture();user.subscriptions[0]={...plan(),cycle:'yearly',packageId:'pkg_g',start:'2026-07-24',prorate:false,paymentEvery:12,prices:[{from:'2026-07-24',price:50000}],payments:[{id:'annual-part',date:'2026-08-01',amount:25000,currency:'PKR',rate:null,note:''}],refunds:[]};await reset(user);await open();await month('2026-09');assert.match(await form().locator('[data-role=cancel-preview]').innerText(),/Earlier bills still owed: Rs 25,000/);await save();assert.deepEqual((await get()).subscriptions[0].payments,user.subscriptions[0].payments);record('Annual cancellation retains the already-started annual balance');
 await open();await form().locator('[name=reason]').fill('');await form().locator('[name=note]').fill('');await page.locator('#search').fill('Cancellation');assert.equal(await form().locator('[name=reason]').inputValue(),'');assert.equal(await form().locator('[name=note]').inputValue(),'');await save();saved=await get();assert.equal(saved.cancel.reason,'');assert.equal(saved.cancel.note,'');record('Empty optional fields stay empty through redraw and save');
 assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({version:'34',checks,errors},null,2));console.log(`Passed ${checks.length} cancellation checks`);await context.close();
 }finally{await browser.close()}
})().catch(e=>{console.error(e);process.exit(1)});
